Backup/Reconinfra_Accounts/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('auth-logout/', views.LogoutView, name="LogoutView" ),
    path('auth-login/', views.LoginView, name="AuthLogin" ),
    path('auth-register/', views.UserRegister, name="Register" ),
    path('referral-link/<str:sponsor_id>', views.ReferralLinkView, name="ReferralLinkView" ),
    path('user-profile/<str:id>/', views.Profile, name="Profile" ),
    path('associate-details/<str:id>/', views.AssociateDetails, name="AssociateDetails" ),
    path('update-bank-details/', views.UpdateBankDetails, name="UpdateBankDetails" ),
    path('change-profile-picture/', views.ChangeProfilePicture, name="ChangeProfilePicture" ),
    path('my-teams/', views.MyTeamsView, name="MyTeamsView" ),
    path('teams-details/<str:account_id>/', views.TeamDetailsView, name="TeamDetailsView" ),
    path('search-team/', views.SearchTeamsView, name="SearchTeamsView" ),
    path('forget-password/', views.ForgetPasswordView, name="ForgetPasswordView" ),
    path('change-password/<token>/', views.ChangePasswordView, name="ChangePasswordView" ),
    path('create-group/', views.CreateGroupView, name="CreateGroupView" ),
    path('group-list/', views.GroupListView, name="GroupListView" ),
    path('assign-group/', views.AssignGroupView, name="AssignGroupView" ),
    path('initialize-group-list/', views.InitializeGroupListView, name="InitializeGroupListView" ),
    path('group-details/<pk>/', views.GroupsAgentListView, name="GroupsAgentListView" ),
    path('edit-facilitator/<str:pk>', views.EditFacilitatorView, name="EditFacilitatorView" ),
    path('get-associate-name/<str:sponsor_id>', views.getAssociateNameBySponsorIdView, name="getAssociateNameBySponsorIdView" ),
    path('export_users_to_csv', views.export_users_to_csv, name="export_users_to_csv" ),
]

Backup/Reconinfra_Home/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.Home, name="Home" ),
    path('about-company/',views.ReconinfraAboutUs, name="ReconinfraAboutUs"),
    path('legal-documents/',views.LegalsDocuments, name="LegalsDocuments"),
    path('golden-city-plot-availability/',views.GoldenCityPlotAvailability, name="GoldenCityPlotAvailability"),
    path('green-valley-plot-availability/',views.GreenValleyPlotAvailability, name="GreenValleyPlotAvailability"),
    path('contact-us/', views.ReconinfraContactUs, name="ReconinfraContactUs"),
    path('company-mission-and-vision/', views.MissionandVision, name="MissionandVision"),
    path('property-details/<str:slug>/', views.PropertiesDetailsView, name="PropertyDetails"),
    path('media-canter/', views.ReconinfraImageGallery, name="ReconinfraImageGallery"),
    path('terms-and-conditions/', views.ReconinfraTermsAndConditions, name="ReconinfraTermsAndConditions"),
    path('privacy-policy/', views.ReconinfraPrivacyPolicy, name="ReconinfraPrivacyPolicy"),
    path('disclaimer/', views.ReconinfraDisclaimer, name="ReconinfraDisclaimer"),
    path('customer-login/', views.CustomerLogin, name="CustomerLogin"),
    path('customer-profile/', views.CustomerProfile, name="CustomerProfile"),
    path('emi-history/', views.EMIHistoryView, name="EMIHistoryView"),
    path('check-plot-availability/<str:slug>/', views.CheckPlotAvailability, name="CheckPlotAvailability"),
    path('test-plot/', views.TestPlotAPI, name="TestPlotAPI"),
]

Reconinfra/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Reconinfra_Home.urls')),
    path('accounts/', include('Reconinfra_Accounts.urls')),
    path('business/', include('Reconinfra_Business.urls')),
    path('app/', include('Reconinfra_Admin_Panel.urls')),

]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('', views.Admin_Panel_Home, name="admin_dashboard" ),
    path('add-property', views.AddProperties, name="AddProperties" ),
    path('property-list', views.PropertyList, name="PropertyList" ),
    path('edit-property/<int:pk>', views.UpdatePropertiesView, name="UpdatePropertiesView" ),
    path('delete-plot/<int:pk>', views.DeletePlotView, name="DeletePlotView" ),
    path('add-plot-images', views.AddPlotImages, name="AddPlotImages" ),
    path('add-gallery-images', views.AddGalleryImage, name="AddGalleryImage" ),
    path('list-gallery-images', views.ListGalleryImages, name="ListGalleryImages" ),
    path('delete-gallery-images/<int:pk>', views.DeleteImageView, name="DeleteImageView" ),
    path('add-plot-availability', views.AddPlotAvailability, name="AddPlotAvailability" ),
    
    path('my-orders', views.MyOrdersView, name="MyOrdersView" ),
    path('get-agent-booked-details/', views.getAgentBookedDetailsView, name="getAgentBookedDetailsView" ),
    path('booking-history', views.BookingHistoryView, name="BookingHistoryView" ),
    path('add-reward', views.AddRewardView, name="AddRewardView" ),
    path('reward-list', views.RewardListView, name="RewardListView" ),
    path('facilitator-list', views.FacilitatorListView, name="FacilitatorListView" ),
    path('transfer-request', views.TransferRequestView, name="TransferRequestView" ),
    path('transfer-request-list', views.TransferRequestListView, name="TransferRequestListView" ),
    path('withdrawals-list', views.WithdrawalsRequestListView, name="WithdrawalsRequestListView" ),
    path('view-withdrawals-details/<int:transfer_request_id>', views.ViewAgentWithrawalsDetailsView, name="ViewAgentWithrawalsDetailsView" ),
    path('activate-id', views.ActivateIdView, name="ActivateIdView" ),
    path('plot-booking', views.PlotBookingView, name="PlotBookingView" ),
    path('update-booking-plot/<int:booking_id>', views.UpdateBookingPlot, name="UpdateBookingPlot" ),
    path('delete-booking-plot/<int:booking_id>', views.DeleteBookingView, name="DeleteBookingView" ),
    path('my-team-tree', views.MyTreeTeamView, name="MyTreeTeamView" ),
    path('get-teams', views.GetAllUsersView, name="GetAllUsersView" ),
    path('import-csv', views.import_csv, name="import_csv" ),
]

Backup/Reconinfra_Accounts/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import UserManager
from django.utils.translation import gettext as _
from django.core.validators import RegexValidator
from django.db.models.signals import pre_save
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.conf import settings


# Create your models here.


class Country(models.Model):
    sortname = models.CharField(max_length=50, null=True)
    name = models.CharField(max_length=50, null=True)
    def __str__(self):
        return self.name

class State(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=50, null=True)
    def __str__(self):
        return self.name

class City(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=50, null=True)
    def __str__(self):
        return self.name

class CustomUser(AbstractUser):
    username = None
    account_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(_('email address'),unique=True)
    phone_number = models.CharField(max_length=17, null=True,)
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    profile_pic = models.ImageField(upload_to='Recon/User/Profile-Picture', null=True, blank=True)
    is_admin = models.BooleanField(default=False)
    is_facilitator = models.BooleanField(default=False)
    is_accountent = models.BooleanField(default=False)
    aadhar_number = models.CharField(max_length=20, null=True, blank=True)
    aadhar_front = models.ImageField(upload_to='Recon/User/Aadhar', null=True, blank=True)
    aadhar_back = models.ImageField(upload_to='Recon/User/Aadhar', null=True, blank=True)
    pan_number = models.CharField(max_length=11, null=True, blank=True)
    pan_front = models.ImageField(upload_to='Recon/User/PAN', null=True, blank=True)
    pan_back = models.ImageField(upload_to='Recon/User/PAN', null=True, blank=True)
    account_holder_name = models.CharField(max_length = 50, null=True, blank=True)
    account_number= models.CharField(max_length=25, null=True, blank=True)
    ACCOUNT_TYPE = (
        ('Saving', 'Saving'),
        ('Current', 'Current')
    )
    account_type = models.CharField(max_length=50, choices=ACCOUNT_TYPE, default='Saving', null=True, blank=True)
    ifsc_code = models.CharField(max_length=15, null=True, blank=True)
    bank_name = models.CharField(max_length=50, null=True, blank=True)
    branch_name = models.CharField(max_length=100, null=True, blank=True)
    country = models.ForeignKey(Country, on_delete=models.DO_NOTHING, null=True)
    state = models.ForeignKey(State, on_delete=models.DO_NOTHING, null=True)
    city = models.ForeignKey(City, on_delete=models.DO_NOTHING, null=True)
    address = models.CharField(max_length=150, null=True)
    referred_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING, related_name='children', null=True, blank=True)
    sponsor_id = models.CharField(max_length = 500, null=True, blank=True)
    is_wallet_active = models.BooleanField(default=False)
    BUSINESS_LEVEL = (
        ('Level1', 'Level1'),
        ('Level2', 'Level2'),
        ('Level3', 'Level3'),
        ('Level4', 'Level4'),
        ('Level5', 'Level5'),
        ('Level6', 'Level6'),
        ('Level7', 'Level7'),
        ('Level8', 'Level8'),
        ('Level9', 'Level9'),
        ('Level10', 'Level10'),
    )
    business_level = models.CharField(max_length=20, null=True, blank=True, choices=BUSINESS_LEVEL, default='Level1')
    forget_password_token = models.CharField(max_length=100, null=True, blank=True)
    
    USERNAME_FIELD = 'email'
    
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):
        return f' {self.first_name} {self.last_name} ({self.sponsor_id})'

    def save(self, *args, **kwargs):  # new
        if not self.sponsor_id:
            self.sponsor_id = generator_sponsor_id()
        return super().save(*args, **kwargs)

import string
import random
def generator_sponsor_id(size=8, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))


class Group(models.Model):
    group_name = models.CharField(max_length=100, null=True, unique=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    def __str__(self):
        return f'{self.group_name}'

class GroupInitialize(models.Model):
    group = models.ForeignKey(Group, on_delete=models.DO_NOTHING, null=True)
    agent = models.ForeignKey(CustomUser, on_delete=models.DO_NOTHING, null=True)
    is_admin = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

Backup/Reconinfra_Business/models.py
from django.db import models

# Create your models here.

Backup/Reconinfra_Home/models.py
from django.db import models

# Create your models here.



class ContactUs(models.Model):
    name = models.CharField(max_length=100, null=True, blank=False)
    phone = models.CharField(max_length=100, null=True, blank=False)
    subject = models.CharField(max_length=100, null=True)
    message = models.TextField(null=True)

    def __str__(self):
        return self.name + ' ' + self.subject

Backup/Reconinfra_Accounts/forms.py
from django import forms
from .models import CustomUser,Group,GroupInitialize
from django.forms import ModelForm, ValidationError

class UserRegisterForm(forms.ModelForm):
    class Meta:
      model = CustomUser
      fields = [
        'first_name', 
        'last_name',
        'email',
        'phone_number',
        'aadhar_number',
        'pan_number',
        'account_holder_name',
        'account_number',
        'account_type',
        'ifsc_code',
        'bank_name',
        'branch_name',
        'country',
        'state',
        'city',
        'address',
        'sponsor_id',
        'password'
      ]
class UpdateRegisterForm(forms.ModelForm):
    class Meta:
      model = CustomUser
      fields = [
        'first_name', 
        'last_name',
        'email',
        'phone_number',
        'aadhar_number',
        'pan_number',
        'account_holder_name',
        'account_number',
        'account_type',
        'ifsc_code',
        'bank_name',
        'branch_name',
        'country',
        'business_level',
        'state',
        'city',
        'address',
        'referred_by',
      
      ]
    
class UserUpdateForm(forms.ModelForm):
  class Meta:
      model = CustomUser
      fields = [
        'profile_pic',
        'first_name', 
        'last_name',
        'email',
        'phone_number',
        'aadhar_number',
        #'aadhar_front',
        #'aadhar_back',
        'pan_number',
        #'pan_front',
        #'pan_back',
        # 'account_holder_name',
        # 'account_number',
        # 'account_type',
        # 'ifsc_code',
        # 'bank_name',
        # 'branch_name',
        # 'country',
        'state',
        'city',
        'address',  
      ]
class UpdateBankDetailsForm(forms.ModelForm):
  class Meta:
    model = CustomUser
    fields = [
        'account_holder_name',
        'account_number',
        'account_type',
        'ifsc_code',
        'bank_name',
        'branch_name',
      ]

class GroupForm(forms.ModelForm):
  class Meta:
    model = Group
    fields = ['group_name']

class GroupInitializeForm(forms.ModelForm):
  class Meta:
    model = GroupInitialize
    fields = ['group','agent','is_admin']
  

Backup/Reconinfra_Admin_Panel/forms.py
from pyexpat import model
from .models import *
from django import forms

class AddPropertyForm(forms.ModelForm):
    class Meta:
        model = Properties
        fields = [
            'name', 
            'location', 
            'city', 
            'plot_map', 
            'plot_types', 
            'description',
            'image_1',
            'image_2',
            'image_3',
            'image_4',
        ]

class PropertyImageForm(forms.ModelForm):
    class Meta:
        model = PropertiesImage
        fields = ['properties', 'image']

class AddPlotAvailabilityForm(forms.ModelForm):
    class Meta:
        model = PlotAvailabilities
        fields = ['properties', 'plot_status', 'plot_dimensions', 'plot_number']


class AddGalleryImagesForm(forms.ModelForm):
    class Meta:
        model = GalleryImages
        fields = ['image']

class RewardForm(forms.ModelForm):
    class Meta:
        model = Reward
        fields = ['product_type','title', 'time_limit', 'business', 'description','product_image']                                           
                                          

class TransferRequestForm(forms.ModelForm):
    class Meta:
        model = TransferRequest
        fields = ['amount']

class WithdrawalsRequestForm(forms.ModelForm):
    class Meta:
        model = TransferRequest
        fields = '__all__'

class PlotBookingForm(forms.ModelForm):
    class Meta:
        model = PlotBooking
        fields = '__all__'

class ActivateIdForm(forms.ModelForm):
    class Meta:
        model = Wallet
        fields = '__all__'

class PlotImageForm(forms.ModelForm):
    class Meta:
        model = PropertiesImage
        fields = '__all__'

class AddPaymentForm(forms.ModelForm):
    class Meta:
        model = EMIHistory
        fields = '__all__'


from django import forms

class CSVUploadForm(forms.Form):
    csv_file = forms.FileField()

Backup/Reconinfra_Home/forms.py
from django import forms
from .models import ContactUs
from Reconinfra_Admin_Panel.models import PlotBooking

class EnquiryForm(forms.ModelForm):
    name = forms.CharField(error_messages = {
                 'required':"Please Enter your Name"
                 })
    class Meta:
        model = ContactUs
        fields = '__all__'

class CustomerLoginForm(forms.ModelForm):
    customer_username = forms.CharField(max_length=30)
    customer_password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = PlotBooking
        fields = ['customer_username', 'customer_password']

Backup/Reconinfra_Business/views.py
from django.shortcuts import render

# Create your views here.
def Business_Home(request):
    pass

Backup/templates/app/user-register.html
<!DOCTYPE html>
<html lang="en" data-theme="light">
	{% load static %}
	{% load my_filter %}
	<!--begin::Head-->
	<head>
		<title>Reconinfra Admin | Become a Facilitator</title>
		<meta charset="utf-8">
		
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
		<link href="/static/app-assets/plugins/global/plugins.bundle.css" rel="stylesheet" type="text/css">
		<link href="/static/app-assets/css/style.bundle.css" rel="stylesheet" type="text/css">
		<style>
            ul.errorlist {
                color: #f1416c;
                list-style: none;
				padding: 0;
            }
			body#kt_body {
				background: url(https://d21dlgmglu11i3.cloudfront.net/assets/uploads/images/1576042243lakecounty.jpeg);
				background-repeat: no-repeat;
				background-size: cover;
				background-attachment: fixed;
			}
			.form-control{
				border: 1px solid #c5d1de;
    			border-radius: 12px;
			}
        </style>
	</head>
	<body id="kt_body" class="app-blank bgi-size-cover bgi-position-center bgi-no-repeat">
		
		<div class="d-flex flex-column flex-root">
			
			<div class="d-flex flex-column flex-column-fluid flex-lg-row">
				
				<!--begin::Body-->
				<div class="d-flex flex-center  p-10 mx-auto">
					<!--begin::Card-->
					<div class="card rounded-3 w-md-700px">
						<!--begin::Card body-->
						<div class="card-body">
							<!--begin::Form-->
							<form method="post" class="form w-100" action="" novalidate>
								<!--begin::Heading-->
								{% csrf_token %}
								<div class="text-center mb-11">
									<!--begin::Title-->
									<img src="/static/app-assets/media/logos/page-loader.png" height="100">
									<h1 class="text-dark fw-bolder mb-3">Recon Group</h1>
									
								</div>
								<!--begin::Heading-->
								
								<!--begin::Separator-->
								<div class="separator separator-content my-14">
									<span class="w-125px text-gray-500 fw-semibold fs-7">Facilitator Form</span>
								</div>
								<!--end::Separator-->
								<!--begin::Input group=-->
								<div class="fv-row mb-8">
									<div class="row">
										<div class="col">
											<label for="prnt_id" class="mb-2">Sponsor ID <span class="text-danger">*</span></label>
											<input type="text" name="sp_id" id="sponsorID" class="form-control bg-transparent" value="{{sponsor_id}}" onkeyup="fetchName()" placeholder="Sponsor ID" required>
											<div id="output"></div>
											{{form.sponsor_id.errors}}
										</div>
									</div>
								</div>
								<div class="fv-row mb-8">
									<div class="row">
										<div class="col-sm-6">
											{{form.first_name|addclass:'form-control bg-transparent'|addplaceholder:'First Name'}}
                                            {{form.first_name.errors}}
										</div>
										<div class="col-sm-6">
											{{form.last_name|addclass:'form-control bg-transparent'|addplaceholder:'Last Name'}}
                                            {{form.last_name.errors}}
                                        </div>
									</div>
								</div>
								<div class="fv-row mb-8">
									<div class="row">
										<div class="col-sm-6">
											{{form.email|addclass:'form-control bg-transparent'|addplaceholder:'Email Address'}}
                                            {{form.email.errors}}
										</div>
										<div class="col-sm-6">
											{{form.phone_number|addclass:'form-control bg-transparent'|addplaceholder:'Phone Number'}}
                                            {{form.phone_number.errors}}
										</div>
									</div>
								</div>
								
								<div class="fv-row mb-8">
									<div class="row">
										<div class="col-sm-6">
											{{form.aadhar_number|addclass:'form-control bg-transparent'|addplaceholder:'Enter Aadhar Number'}}
                                            {{form.aadhar_number.errors}}
										</div>
										<div class="col-sm-6">
											{{form.pan_number|addclass:'form-control bg-transparent'|addplaceholder:'PAN Card Number'}}
                                            {{form.pan_number.errors}}
										</div>
									</div>
								</div>
								
                                <div class="separator separator-content my-14">
									<span class="w-125px text-gray-500 fw-semibold fs-7">Financial Details</span>
								</div>
								<div class="fv-row mb-8">
									<div class="row">
										<div class="col-sm-6">
											{{form.account_holder_name|addclass:'form-control bg-transparent'|addplaceholder:'Account Holder Name'}}
                                            {{form.account_holder_name.errors}}
										</div>
										<div class="col-sm-6">
											{{form.account_number|addclass:'form-control bg-transparent'|addplaceholder:'Account Number'}}
                                            {{form.account_number.errors}}
										</div>
									</div>
								</div>
								<div class="fv-row mb-8">
									<div class="row">
										<div class="col-sm-6">
											{{form.account_type|addclass:'form-control bg-transparent'|addplaceholder:'Account Type'}}
                                            {{form.account_type.errors}}
										</div>
										<div class="col-sm-6">
											{{form.ifsc_code|addclass:'form-control bg-transparent'|addplaceholder:'IFSC Code'}}
                                            {{form.ifsc_code.errors}}
										</div>
									</div>
								</div>
								<div class="fv-row mb-8">
									<div class="row">
										<div class="col-sm-6">
											{{form.bank_name|addclass:'form-control bg-transparent'|addplaceholder:'Bank Name'}}
                                            {{form.bank_name.errors}}
										</div>
										<div class="col-sm-6">
											{{form.branch_name|addclass:'form-control bg-transparent'|addplaceholder:'Branch Name'}}
                                            {{form.branch_name.errors}}
										</div>
									</div>
								</div>
                                <div class="separator separator-content my-14">
									<span class="w-125px text-gray-500 fw-semibold fs-7">Facilitator Details</span>
								</div>
								<div class="fv-row mb-8">
									<div class="row">
										<div class="col-sm-6">
											{{form.country|addclass:'form-control bg-transparent'|addplaceholder:'Country'|addid:'country'}}
                                            {{form.country.errors}}
										</div>
										<div class="col-sm-6">
											{{form.state|addclass:'form-control bg-transparent'|addplaceholder:'State'|addid:'state'}}
                                            {{form.state.errors}}
										</div>
									</div>
								</div>
								<div class="fv-row mb-8">
									<div class="row">
										<div class="col-sm-6">
											{{form.city|addclass:'form-control bg-transparent'|addplaceholder:'City'|addid:'city'}}
                                            {{form.city.errors}}
										</div>
										<div class="col-sm-6">
											{{form.address|addclass:'form-control bg-transparent'|addplaceholder:'Full Address'}}
                                            {{form.address.errors}}
										</div>
									</div>
								</div>
								<!--begin::Input group-->
								<div class="fv-row mb-8" data-kt-password-meter="true">
									<!--begin::Wrapper-->
									<div class="mb-1">
										<!--begin::Input wrapper-->
										<div class="position-relative mb-3">
                                            {{form.password|addclass:'form-control bg-transparent'|addplaceholder:'Password'|addid:'password'}}
											{{form.password.errors}}
											<span class="btn btn-sm btn-icon position-absolute translate-middle top-50 end-0 me-n2" data-kt-password-meter-control="visibility">
												<i class="bi bi-eye-slash fs-2"></i>
												<i class="bi bi-eye fs-2 d-none"></i>
											</span>
										</div>
										<!--end::Input wrapper-->
										<!--begin::Meter-->
										<!-- <div class="d-flex align-items-center mb-3" data-kt-password-meter-control="highlight">
											<div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
											<div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
											<div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px me-2"></div>
											<div class="flex-grow-1 bg-secondary bg-active-success rounded h-5px"></div>
										</div> -->
										<!--end::Meter-->
									</div>
									<!-- <div class="text-muted">Use 8 or more characters with a mix of letters, numbers & symbols.</div> -->
									<!--end::Hint-->
								</div>
								<div class="fv-row mb-8">
									<!--begin::Repeat Password-->
									<input placeholder="Repeat Password" name="confirm_password" id="confirm_password" type="password" autocomplete="off" class="form-control bg-transparent" required>
									<!--end::Repeat Password-->
								</div>
								<!--end::Input group=-->
								<!--begin::Accept-->
								<!-- <div class="fv-row mb-8">
									<label class="form-check form-check-inline">
										<input class="form-check-input" type="checkbox" name="toc" value="1">
										<span class="form-check-label fw-semibold text-gray-700 fs-base ms-1">I Accept the 
										<a href="#" class="ms-1 link-primary">Terms</a></span>
									</label>
								</div> -->
								
								<div class="d-grid mb-10">
									<button type="submit" class="btn btn-primary"> Submit</button>
								</div>
								
								<div class="text-gray-500 text-center fw-semibold fs-6">Already have an Account? 
								<a href="{% url 'AuthLogin' %}" class="link-primary fw-semibold">Sign in</a></div>
								
							</form>
							
						</div>
						
					</div>
					
				</div>
				
			</div>
			<!--end::Authentication - Sign-up-->
		</div>
		
		<script src="/static/app-assets/plugins/global/plugins.bundle.js"></script>
		<script src="/static/app-assets/js/scripts.bundle.js"></script>
		<script src="/static/app-assets/js/custom/authentication/sign-in/general.js"></script>
	
		<script>
			function fetchName() {
				const idInput = document.getElementById("sponsorID");
				const nameContainer = document.getElementById("output");
				const id = idInput.value;
				console.log(id);
				if (id.length === 8) {
					console.log("request send");
					fetch(`/accounts/get-associate-name/${id}`)
						.then(response => response.json())
						.then(data => {
							nameContainer.innerHTML = `<span class="text-success" style="font-style: italic;font-family: sans-serif;">${data.name}</span>`;
						})
						.catch(error => {
							console.error('Error:', error);
						});
				} else {
					nameContainer.innerHTML = "";
				}
			}
			$(document).ready(function() {
				const idInput = document.getElementById("sponsorID");
				const nameContainer = document.getElementById("output");
				const id = idInput.value;
				console.log(id);
				if (id.length === 8) {
					console.log("request send");
					fetch(`/accounts/get-associate-name/${id}`)
						.then(response => response.json())
						.then(data => {
							nameContainer.innerHTML = `<span class="text-success" style="font-style: italic;font-family: sans-serif;">${data.name}</span>`;
						})
						.catch(error => {
							console.error('Error:', error);
						});
				} else {
					nameContainer.innerHTML = "";
				}
				$("#id_account_type").select2({
					placeholder: "Select account type"
				});
				
				$("#country").select2({
					placeholder: "Select Country"
				});
				$("#state").select2({
					placeholder: "Select State"
				});
				$("#city").select2({
					placeholder: "Select City"
				});
				$("#payment_method").select2({
					placeholder: "Payment Method"
				});
				$("#emi_installments").select2({
					placeholder: "EMI Installment"
				});
				
			});
		</script>
		<!--end::Custom Javascript-->
	</body>
	
</html>